# Generated by Django 5.0.4 on 2024-06-02 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
    ]
